name: gh-pages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27
          elixir-version: 1.17

      - run: pwsh scripts/init.ps1

      - run: pwsh scripts/build.ps1

      - uses: actions/upload-artifact@v4
        with:
          name: gh-pages
          path: priv/static
          retention-days: 30

  push:
    needs: build
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: gh-pages
          path: gh-pages

      - id: hash
        run: echo "::set-output name=hash::$(git rev-parse HEAD)"

      - uses: peaceiris/actions-gh-pages@v4
        if: ${{ steps.hash.outputs.hash != github.event.before }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
